close all
figure
set(gcf,'color','w');

names = {'TaiwanNew/TaiwanDataPartial145.mat',...
    'ClanAlpineNevadaNew/ClanAlpineDataPartial145.mat',...
    'DaqingShanNew/DaqingDataPartial145.mat', ...
    'FinisterreNew/FinisterreDataPartial145.mat',...
    'Humboldt_NevadaNew/HumboldtDataPartial145.mat',...
    'InyoNew/InyoDataPartial145.mat',...
    'KammanasieNew/KammanasieDataPartial145.mat',...
    'LuliangNew/LuliangDataPartial145.mat', ...
    'PanamintNew/PanamintDataPartial145.mat',...
    'SakhalinNew/SakhalinDataPartial145.mat',...
    'SierraDelValleFertileNew/Fertile1DataPartial145.mat',...
    'SierraMadreDelSurNew/DelSurDataPartial145.mat',...
    'SierraNevadaSpainNew/SierraNevadaDataPartial145.mat',...
    'SierraPieDePaloNew/Fertile2DataPartial145.mat',...
    'ToanoRangeNew/ToanoDataPartial145.mat',...
    'TroodosNew/TroodosDataPartial145.mat',...
    'TsugaruNew/TsugaruDataPartial145.mat',...
    'YoroNew/YoroDataPartial145.mat'};

titles = {'Cenral Mountain Range, Taiwan',...
'Clan Alpine Mountains, Nevada',...
'Daquing Shan,  China',...
'Finisterre Range, Papua New Guinea',...
'Humboldt Range, Nevada',...
'Inyo Mountains, California',...
'Kammanassie Mountains, South Africa',... 
'Lüliang Mountains, China' ,...
'Panamint Range, California',...
'Sakhalin Mountains, south Sakhalin Island, Russia',...
'Sierra del Valle Fértil, Argentina',...
'Sierra Madre del Sur, Mexico',...
'Sierra Nevada,  Spain',...
'Sierra Pie de Palo, Argentina',...
'Toano Range, Nevada',...
'Troodos Mountains, Cyprus',...
'Tsugaru peninsula, Japan',...
'Yoro Mountains, Japan'};

toRotate = [1,0,0,0,1,1,0,0,1,1,1,0,0,1,1,0,1,1];



for i = 1:length(names)
    load(names{i});
    minx=min(ST_Selected.x);
    miny=min(ST_Selected.y);
    maxx=max(ST_Selected.x);
    maxy=max(ST_Selected.y);
    DEMsub = crop(DEM,[minx minx maxx maxx],[miny maxy miny maxy]);
    subplot(9,2,i)
    imageschs(DEMsub,[],'usepermanent',true,'colormap','gray');
    set(gca,'XTick',[], 'YTick', [])
    colorbar off
    hold on
    plot(ST_Selected,'c')
    if toRotate(i)
        camroll(90)
    end
    ScaleBar('color','w')
    title(titles{i})
end

% load(names)
% minx=min(ST_Selected.x);
% miny=min(ST_Selected.y);
% maxx=max(ST_Selected.x);
% maxy=max(ST_Selected.y);
% DEMsub = crop(DEM,[minx minx maxx maxx],[miny maxy miny maxy]);
% subplot(6,3,1)
% imageschs(DEMsub,[],'usepermanent',true,'colormap','gray');
% set(gca,'XTick',[], 'YTick', [])
% colorbar off
% hold on
% plot(ST_Selected,'c')
% ScaleBar('color','w')
% 
% 
% load('ClanAlpineNevadaNew/ClanAlpineDataPartial145.mat')
% minx=min(ST_Selected.x);
% miny=min(ST_Selected.y);
% maxx=max(ST_Selected.x);
% maxy=max(ST_Selected.y);
% DEMsub = crop(DEM,[minx minx maxx maxx],[miny maxy miny maxy]);
% subplot(6,3,2)
% imageschs(DEMsub,[],'usepermanent',true,'colormap','gray');
% hold on
% plot(ST_Selected,'c')
% ScaleBar('color','w')




% load('FinisterreDataPartial145.mat')
% L  = drainagebasins(FD,ST_Selected);
% E = GRIDobj(DEMc);
% E.Z = L.Z~= 0;
% DEMs = crop(DEMc,E);
% [MS,x,y] = GRIDobj2polygon(L);
% DEMbas = clip(DEMs,MS);
% imageschs(DEMbas,[],'usepermanent',true,'colormap','gray');
% hold on
% plot(ST_Selected,'b')
% ScaleBar
% %plot(D2,'limit',[1000 inf],'color','w')